Repository sku-Gunbam/Android, pull requests merged in 2023-10, with the labels that each got.

#19 Feature/17 깃 세팅 메세지 업데이트
  .gitignore
  .gitmessage.txt
Labels: docs

#24 feat: 프로필 이미지 추가/변경 기능 추가
  app/src/main/java/military/gunbam/view/fragment/CalculatorFragment.java
  app/src/main/res/layout/fragment_calculator_main.xml
Labels: feature

#25 chore: 구글 콘솔에 앱 배포
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-v24/ic_action_info.png
  app/src/main/res/menu/bottom_navigation.xml
  app/src/main/res/menu/post.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: chore

#26 feat: 홈화면 총알 버튼으로 게시판 전환
  app/src/main/java/military/gunbam/view/fragment/mainBoardListFragment.java
  app/src/main/java/military/gunbam/view/fragment/main_Board_list_Fragment.java
  app/src/main/res/layout/fragment_home.xml
Labels: feature

#28 feat: 관리자 페이지 테스트 게시물 추가 개선
  app/src/main/java/military/gunbam/view/activity/AdminActivity.java
Labels: feature

#29 feat: 게시물 수정 삭제 기능
  app/src/main/java/military/gunbam/view/adapter/BoardListAdapter.java
  app/src/main/java/military/gunbam/view/adapter/HomeAdapter.java
  app/src/main/res/layout/post_item.xml
Labels: feature

#33 !HOTFIX: merge 버그 수정
  app/src/main/java/military/gunbam/view/activity/AdminActivity.java
  app/src/main/java/military/gunbam/view/activity/MainActivity.java
  app/src/main/java/military/gunbam/view/adapter/BoardListAdapter.java
  app/src/main/java/military/gunbam/view/adapter/HomeAdapter.java
  app/src/main/res/layout/fragment_calculator_main.xml
  app/src/main/res/values/strings.xml
Labels: FIX !!
